export const blogsData = [
    {
      id: 22,
      blogName: "This is blog 22",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 21,
      blogName: "This is blog 21",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 20,
      blogName: "This is blog 20",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 19,
      blogName: "This is blog 19",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 18,
      blogName: "This is blog 18",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 17,
      blogName: "This is blog 17",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 16,
      blogName: "This is blog 16",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 15,
      blogName: "This is blog 15",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 14,
      blogName: "This is blog 14",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 13,
      blogName: "This is blog 13",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 12,
      blogName: "This is blog 12",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 11,
      blogName: "This is blog 11",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 10,
      blogName: "This is blog 10",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 9,
      blogName: "This is blog 9",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 8,
      blogName: "This is blog 8",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 7,
      blogName: "This is blog 7",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id:5,
      blogName: "This is blog 5",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id:4,
      blogName: "This is blog 4",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 3,
      blogName: "This is blog 3",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id:2,
      blogName: "This is blog 2",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    },
    {
      id: 1,
      blogName: "This is blog 1",
      blogPublishDate: "Published 10/10/2023",
      blogLink: '/Aboutvision',
    }
]